---
# Copyright 2026 Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: include default variables
  ansible.builtin.include_vars: ../vars/main.yml

- name: include release specific variables
  ansible.builtin.include_vars: "{{ loop_var }}"
  loop: "{{ query('first_found', params) }}"
  loop_control:
    loop_var: loop_var
  vars:
    params:
      files:
        - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution_version'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      paths:
        - ../vars
      skip: true

- name: include release specific tasks
  ansible.builtin.include_tasks: "{{ loop_var }}"
  loop: "{{ query('first_found', params) }}"
  loop_control:
    loop_var: loop_var
  vars:
    params:
      files:
        - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution_version'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      paths:
        - .
      skip: true

- name: prepare directories
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: "{{ item.state | default('directory') }}"
  loop:
    - { dest: /etc/kubernetes/charts }
  when: inventory_hostname == groups['kube_master'][0]

- name: rsync directories
  ansible.posix.synchronize:
    dest: "{{ item.dest }}"
    src: "{{ item.src | default('./files' + item.dest + '/') }}"
    archive: true
    delete: true
    owner: false
    group: false
  loop:
    - { dest: /etc/kubernetes/charts/nginx-gateway-fabric }
  when: inventory_hostname == groups['kube_master'][0]

- name: copy templates
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ item.src | default('./templates' + item.dest + '.j2') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - { dest: /etc/kubernetes/charts/nginx-gateway-fabric.values.yaml }
  when: inventory_hostname == groups['kube_master'][0]

- name: helm install
  kubernetes.core.helm:
    release_name: "{{ helm_nginx_gateway_fabric_helm_release_name }}"
    release_namespace: "{{ helm_nginx_gateway_fabric_helm_release_namespace }}"
    chart_ref: /etc/kubernetes/charts/nginx-gateway-fabric
    values_files: /etc/kubernetes/charts/nginx-gateway-fabric.values.yaml
    create_namespace: true
    state: present
    wait: true
  when: inventory_hostname == groups['kube_master'][0]
  register: result
  changed_when: result is not succeeded
  until: result is succeeded
  retries: 60

- name: kubectl create GatewayClass
  vars:
    ansible_python_interpreter: python3
  kubernetes.core.k8s:
    state: present
    wait: true
    definition:
      apiVersion: gateway.networking.k8s.io/v1
      kind: GatewayClass
      metadata:
        name: nginx-gateway
      spec:
        controllerName: gateway.envoyproxy.io/gatewayclass-controller
  when: inventory_hostname == groups['kube_master'][0]
  register: result
  changed_when: result is not succeeded
  until: result is succeeded
  retries: 60

- name: kubectl create Gateway
  vars:
    ansible_python_interpreter: python3
  kubernetes.core.k8s:
    state: present
    wait: true
    definition:
      apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      metadata:
        name: nginx-gateway
        namespace: "{{ helm_nginx_gateway_fabric_helm_release_namespace }}"
      spec:
        gatewayClassName: nginx
        allowedListeners:
          namespaces:
            from: All
        listeners:
          - name: http
            protocol: HTTP
            port: 80
            allowedRoutes:
              namespaces:
                from: All
          - name: https
            protocol: HTTPS
            port: 443
            allowedRoutes:
              namespaces:
                from: All
            tls:
              certificateRefs:
                - name: server-tls
                  kind: Secret
                  group: ""
  when: inventory_hostname == groups['kube_master'][0]
  register: result
  changed_when: result is not succeeded
  until: result is succeeded
  retries: 60

- name: kubectl apply SnippetsPolicy
  vars:
    ansible_python_interpreter: python3
  kubernetes.core.k8s:
    state: present
    wait: true
    definition:
      apiVersion: gateway.nginx.org/v1alpha1
      kind: SnippetsPolicy
      metadata:
        name: nginx-gateway
        namespace: "{{ helm_nginx_gateway_fabric_helm_release_namespace }}"
      spec:
        targetRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: nginx-gateway
        snippets:
          - context: http
            value: |
              gzip on;
              proxy_buffering on;
              proxy_cache_path /var/cache/nginx/proxy_cache levels=1:2 keys_zone=cache:10m max_size=128m inactive=1m use_temp_path=off;
              proxy_cache_key '$scheme$request_method$host$request_uri$http_origin';
              map $upstream_cache_status $cache_status_header {
                  'HIT'         'nginx-gateway; hit';
                  'STALE'       'nginx-gateway; hit; fwd=stale';
                  'UPDATING'    'nginx-gateway; hit; fwd=stale';
                  'MISS'        'nginx-gateway; fwd=miss; stored';
                  'EXPIRED'     'nginx-gateway; fwd=stale; stored';
                  'BYPASS'      'nginx-gateway; fwd=bypass';
                  'REVALIDATED' 'nginx-gateway; hit; fwd=stale';
                  default       'nginx-gateway; fwd=request';
              }
              map $http_origin $allow_origin {
                  "~^https?://" "$http_origin";
                  default "*";
              }
              map $allow_origin $allow_credentials {
                  "*"     "";
                  default "true";
              }
          - context: http.server.location
            value: |
              proxy_cache cache;
              proxy_cache_valid 200 1s;
              proxy_cache_use_stale updating error timeout http_500 http_502 http_503 http_504;
              proxy_cache_background_update on;
              proxy_cache_lock on;
              proxy_ignore_headers Set-Cookie Cache-Control Expires;
              proxy_hide_header Cache-Control;
              proxy_hide_header Vary;
              proxy_hide_header Access-Control-Allow-Origin;
              proxy_hide_header Access-Control-Allow-Credentials;
              add_header 'Strict-Transport-Security' 'max-age=31536000; includeSubDomains' always;
              add_header 'Cache-Status' '$cache_status_header' always;
              add_header 'Cache-Control' 'public, max-age=1, stale-while-revalidate=59' always;
              add_header 'CDN-Cache-Control' 'public, max-age=1, stale-while-revalidate=59' always;
              add_header 'Access-Control-Allow-Origin' '$allow_origin' always;
              add_header 'Access-Control-Allow-Credentials' '$allow_credentials' always;
              add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
              add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, Accept, Origin, X-Requested-With' always;
              add_header 'Vary' 'Accept-Encoding, Origin' always;
  when: inventory_hostname == groups['kube_master'][0]
  register: result
  changed_when: result is not succeeded
  until: result is succeeded
  retries: 60
